nodes:
  - id: firewall
    label: "FIREWALL - FW_KLASSMATT - INTEGRA"
    shape: rect
    class: firewall

  - id: appservers
    label: "APPSERVERS"
    shape: rect
    class: backend

  - id: SERVER - KLASS-WEB-01
    label: "SERVER - KLASS-WEB-01"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-02
    label: "SERVER - KLASS-WEB-02"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-03
    label: "SERVER - KLASS-WEB-03"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-04
    label: "SERVER - KLASS-WEB-04"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-05
    label: "SERVER - KLASS-WEB-05"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-06
    label: "SERVER - KLASS-WEB-06"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-07
    label: "SERVER - KLASS-WEB-07"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-01
    label: "SERVER - KLASS-WEB-09"
    shape: rect
    class: server

  - id: SERVER - KLASS-WEB-10
    label: "SERVER - KLASS-WEB-10"
    shape: rect
    class: server

edges:
  - from: firewall
    to: appservers

  - from: appservers
    to: SERVER - KLASS-WEB-01
  - from: appservers
    to: SERVER - KLASS-WEB-02
  - from: appservers
    to: SERVER - KLASS-WEB-03
  - from: appservers
    to: SERVER - KLASS-WEB-04
  - from: appservers
    to: SERVER - KLASS-WEB-05
  - from: appservers
    to: SERVER - KLASS-WEB-06
  - from: appservers
    to: SERVER - KLASS-WEB-07
  - from: appservers
    to: SERVER - KLASS-WEB-09
  - from: appservers
    to: SERVER - KLASS-WEB-10
